# Generated by Django 3.2.4 on 2021-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('num_subscribers', models.IntegerField(default=0)),
                ('num_review', models.IntegerField(default=0)),
                ('num_lectures', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('content_duration', models.FloatField(default=0)),
            ],
        ),
    ]
