# Generated by Django 3.2.9 on 2021-12-08 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='num_review',
            new_name='num_reviews',
        ),
        migrations.AddField(
            model_name='course',
            name='published_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
